#!/bin/bash

is_installed() {
	command -v "$1" > /dev/null 2>&1
}

is_bash_completion_installed() {
	test -f /usr/share/bash-completion/bash_completion || test -f /etc/bash_completion
}

required=()

is_installed vim || required+=(vim)
is_installed tmux || required+=(tmux)
is_installed git || required+=(git)
is_installed notify-send || required+=(libnotify)
is_installed ctags || required+=(ctags)
is_bash_completion_installed || required+=(bash-completion)

if [ -n "$required" ]; then
	echo "Required dependencies: ${required[@]}"
	exit 1
fi

for src in bash editorconfig git mercurial tmux vim; do
	cp -irvT $src $HOME
done
