#!/bin/bash

set -eo pipefail

is_installed() {
	command -v "$1" > /dev/null 2>&1
}

is_bash_completion_installed() {
	test -f /usr/share/bash-completion/bash_completion || test -f /etc/bash_completion
}

print_ok() {
	echo -e "\033[01;32m$1\033[00m"
}

pre_install() {
	# Some files need to be placed inside the directory trees created by some applications
	#   eg: ~/.config/xyz/user/config/{CONFIG}
	#
	# stow creates symlinks to the files in this repo if the directory tree already exists:
	#   ~/.config/xyz/user/config/local.cfg -> dotfiles/xyz/.config/xyz/user/config/local.cfg
	# and creates a symlink to the parent directory otherwise:
	#   ~/.config/xyz -> dotfiles/xyz/.config/xyz
	#
	# I don't want to put all application-dependant files in this repo, only the configuration files, so to make
	# sure stow creates the symlinks correctly, even if the application is not installed or has never been run yet,
	# I precreate those directory trees here.
	mkdir -p ~/.local/share/icons
	mkdir -p ~/.config/sublime-text/Packages/User
	mkdir -p ~/.config/JetBrains/IntelliJIdea/keymaps
	mkdir -p ~/.config/JetBrains/IntelliJIdea/options/linux
}


required=()

is_installed stow || required+=(stow)
is_installed vim || required+=(vim)
is_installed tmux || required+=(tmux)
is_installed git || required+=(git)
is_installed notify-send || required+=(libnotify)
is_installed ctags || required+=(ctags)
is_installed editorconfig || required+=(editorconfig)
is_installed fzf || required+=(fzf)
is_installed xsel || is_installed xclip || is_installed wl-clipboard || required+=('xsel|xclip|wl-clipboard')
is_bash_completion_installed || required+=(bash-completion)

if [ -n "$required" ]; then
	echo "Required dependencies: ${required[@]}"
	exit 1
fi

pre_install

for symlink in alacritty bash bin editorconfig fonts git icons jetbrains mercurial nautilus sublime tmux vim; do
	stow -v -t $HOME $symlink
done

echo
print_ok "Dotfiles installed correctly"
