# ~/.bash_profile: executed by the command interpreter for login shells
# ~/.profile is not read by bash(1), if ~/.bash_profile or ~/.bash_login exists.
#
# Do NOT edit this file directly!  Edit .profile instead.
#
# It is required because some distros (arch and others) add one by default
# that take preference to .profile and do not loads it on login shells.

[[ -f ~/.profile ]] && . ~/.profile
[[ -f ~/.bashrc ]] && . ~/.bashrc
